apiVersion: v1
kind: Service
metadata:
  name: cryptoclub-chatbot
  labels:
    app: cryptoclub-chatbot
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: cryptoclub-chatbot
