name: Build Docker Image

on:
  push:
    branches:
      - "main"

# permissions:
#   id-token: write
#   contents: read

jobs:
  build:
    # Builds image from Dockerfile
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Build, tag, and push(*) container image
      env:
        IMAGE_REPO: docker.io/mwthink/cryptoclubtx-chatbot
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $IMAGE_REPO:$IMAGE_TAG .
        docker push $IMAGE_REPO:$IMAGE_TAG
