name: Build Docker Image

on:
  push:
    branches:
      - "main"

# permissions:
#   id-token: write
#   contents: read

jobs:
  build:
    # Builds image from Dockerfile
    name: Build image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    
    # Multiarch info from https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: docker.io/mwthink/cryptoclubtx-chatbot:latest,docker.io/mwthink/cryptoclubtx-chatbot:${{ github.sha }}
